version: '3.8'

services:
  switchboard:
    build: .
    read_only: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT}:8080"
    environment:
      - PORT=8080
    volumes:
      - ./config.json:/root/config.json:ro
    restart: on-failure:10
